THEMES = {
    "Dark": {
        "window_bg": "#222",
        "toolbar_bg": "#222",
        "toolbar_fg": "#eee",
        "tab_bg": "#4b4b4b",
        "tab_fg": "#ddd",
        "tab_selected_bg": "#1a8cff",
        "tab_selected_fg": "#fff",
        "bookmark_bg": "#222",
        "bookmark_fg": "#ccc",
        "status_bg": "#222",
        "status_fg": "#eee",
    },
    "Light": {
        "window_bg": "#f5f5f5",
        "toolbar_bg": "#eee",
        "toolbar_fg": "#222",
        "tab_bg": "#ddd",
        "tab_fg": "#222",
        "tab_selected_bg": "#1a8cff",
        "tab_selected_fg": "#fff",
        "bookmark_bg": "#eee",
        "bookmark_fg": "#222",
        "status_bg": "#eee",
        "status_fg": "#222",
    },
    "Dracula": {
        "window_bg": "#282a36",
        "toolbar_bg": "#44475a",
        "toolbar_fg": "#f8f8f2",
        "tab_bg": "#6272a4",
        "tab_fg": "#f8f8f2",
        "tab_selected_bg": "#ff79c6",
        "tab_selected_fg": "#282a36",
        "bookmark_bg": "#44475a",
        "bookmark_fg": "#f8f8f2",
        "status_bg": "#282a36",
        "status_fg": "#f8f8f2",
    },
    "Solarized Dark": {
        "window_bg": "#002b36",
        "toolbar_bg": "#073642",
        "toolbar_fg": "#839496",
        "tab_bg": "#586e75",
        "tab_fg": "#eee8d5",
        "tab_selected_bg": "#268bd2",
        "tab_selected_fg": "#fdf6e3",
        "bookmark_bg": "#073642",
        "bookmark_fg": "#839496",
        "status_bg": "#002b36",
        "status_fg": "#839496",
    },
    "Solarized Light": {
        "window_bg": "#fdf6e3",
        "toolbar_bg": "#eee8d5",
        "toolbar_fg": "#657b83",
        "tab_bg": "#93a1a1",
        "tab_fg": "#073642",
        "tab_selected_bg": "#268bd2",
        "tab_selected_fg": "#fdf6e3",
        "bookmark_bg": "#eee8d5",
        "bookmark_fg": "#657b83",
        "status_bg": "#fdf6e3",
        "status_fg": "#657b83",
    },
    "Oceanic Blue": {
        "window_bg": "#1B2B34",
        "toolbar_bg": "#343D46",
        "toolbar_fg": "#CDD3DE",
        "tab_bg": "#4F5B66",
        "tab_fg": "#CDD3DE",
        "tab_selected_bg": "#6699CC",
        "tab_selected_fg": "#FFF",
        "bookmark_bg": "#343D46",
        "bookmark_fg": "#CDD3DE",
        "status_bg": "#1B2B34",
        "status_fg": "#CDD3DE",
    },
    "High Contrast": {
        "window_bg": "#000",
        "toolbar_bg": "#000",
        "toolbar_fg": "#fff",
        "tab_bg": "#333",
        "tab_fg": "#fff",
        "tab_selected_bg": "#ff0",
        "tab_selected_fg": "#000",
        "bookmark_bg": "#000",
        "bookmark_fg": "#fff",
        "status_bg": "#000",
        "status_fg": "#fff",
    },
}
